name: workflow name

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bench:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: microsoft/typescript
          path: target

      - run: go run test.go target

      - run: python test.py target
